id: P008034
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2PD20797
  title: ཚུལ་ཁྲིམས་བསྟོད་པ་བླང་དོར་གསལ་བྱེད་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  volumes:
    7f930d5e237040318350ffbd46944b57:
      image_group_id: I2PD20857
      title: Volume 1 of
      volume_number: 1
      total_pages: 156
      base_file: v001.txt
