id: P008034
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD20797
  title: ཚུལ་ཁྲིམས་བསྟོད་པ་བླང་དོར་གསལ་བྱེད་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  volumes:
    f559e56654374afa94f07468ea82f2ed:
      image_group_id: I2PD20857
      title: ''
      volume_number: 1
      total_pages: 156
ebook_metadata:
  title: ཚུལ་ཁྲིམས་བསྟོད་པ་བླང་དོར་གསལ་བྱེད་རྩ་བ་དང་འགྲེལ་པ།
  author: ''
  sku: P008034
  cover: cover.jpg
  layers:
  - pagination
