id: I34E6B5CA
legacy_id: P008034
ocr_import_info:
  bdrc_scan_id: W2PD20797
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T02:02:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:09:03.546914+00:00'
last_modified: 2022-09-03 19:09:10.103793
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD20797
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD20797
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚུལ་ཁྲིམས་བསྟོད་པ་བླང་དོར་གསལ་བྱེད་རྩ་བ་དང་འགྲེལ་པ།
  author: ཨོ་རྒྱན་བསྟན་འཛིན་ནོར་བུ།
statistics:
  ocr_word_mean_confidence_index: 0.8958279452998849
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I2PD20857:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20857
      total_pages: 156
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD20857.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8958279452998849
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
